suzkiee/battleship

- lib/cell.rb
- spec/cell_spec.rb
Adds the following methods
- initialize 
- empty? 
- place_ship 
- fired_upon? 
- fire_upon 
- initialize: initializes cell
- empty?: checks if cell is empty
- place_ship: places ship instance in cell
- fired_upon? : checks if cell was fired upon
- fire_upon: fires upon cell
Features 
Test have been created for each method
> Cell class

- lib/cell.rb
- spec/cell_spec.rb
cell.render method 
Complete functionality for render method by adding conditions that check the if a cell is hit, a cell is fired upon but empty, a cell is fired upon and the ship is sunk and shows hidden ships when needed.
feature
Test written for each cell condition.
> Complete functionality for render method

- lib/board.rb
- spec/board_spec.rb
board.rb
board_spec.rb
Creates a board class
feature
Tests written for initialize method
> Create Board class

- lib/board.rb
- spec/board_spec.rb
`#place`
Adds place method to place ship on board when placement is valid.
feature 
Tested that placement occurs for valid placements and placement does not work for invalid placements
> Complete and test place method

- lib/board.rb
- spec/board_spec.rb
render method
Renders board with cells rendered (empty tests completed)
feature
Tests written for empty board to render properly
> Create render method for Board class

- lib/board.rb
- spec/board_spec.rb
render method
Completes functionality of render method 
feature update
Made tests for each condition of the board to check that it renders cells accordingly.
> Complete functionality and tests for render method

- lib/setup.rb
- spec/setup_spec.rb
Adds setup class
Creates a setup class to handle board setup and initial placements 
feature 
Initialize method was tested
> Create setup class

- lib/board.rb
- spec/board_spec.rb
Board class valid_placement, generate_cells methods
Refactors valid_placement and generate_cells methods
Refactor
Original tests used for valid_placement conditions and initialization
> Refactor valid_placement and cell creation for Board class

- lib/board.rb
- lib/setup.rb
- spec/setup_spec.rb
place_computer_ships
Completes logic for randomizing computer ship coordinates and renders board. 
feature/setup_class
Tests that the return is an array of randomized valid coordiantes
> Complete place_computer_ship method

- lib/setup.rb
- spec/setup_spec.rb
setup class 
Completes player_place_ship method and run_setup method 
feature
Testing not required because of user input
> Complete functionality for setup class

- lib/setup.rb
- lib/turn.rb
- runner_test.rb
- spec/turn_spec.rb
Turn class
Creates method to display player boards and adds method to allow user to shoot at computer board.
feature 
Created a test runner file to test methods where user input is given.
> Update turn class with display and user shot methods

- lib/board.rb
- lib/turn.rb
- runner_test.rb
Turn class 
Completes functionality of Turn class by adding computer shoots method 
feature
We used the runner_test.rb to check the output and user input logic.
> Complete functionality for turn class

- lib/board.rb
- lib/game.rb
- lib/turn.rb
- runner_test.rb
- spec/game_spec.rb
Game class
Creates Game class files, adds initial methods 
feature 
Created tests for logic not requiring user input
> Create Game class with helper methods

- lib/game.rb
- lib/turn.rb
- runner_test.rb
- spec/game_spec.rb
- spec/turn_spec.rb
take_turns method
Allows game to loop computer turns and user turns until there is a winner. 
feature 
We used a test runner file and ran the game in the terminal
> Complete functionality for take_turns

- lib/game.rb
- lib/setup.rb
- lib/turn.rb
- runner_test.rb
- spec/setup_spec.rb
- spec/turn_spec.rb
Game class, Turn class, some small syntax cleanup
Adds celebrate_winner method and fixes issues with the workflow caused by Turn class method structure.
feature and bug fixes
added test for method in Turn class, used user_input to tests other functions
> Add celebrate_winner method and fix game flow bug

- lib/board.rb
- lib/game.rb
- lib/setup.rb
- lib/turn.rb
- spec/board_spec.rb
- spec/game_spec.rb
- spec/setup_spec.rb
- spec/ship_spec.rb
- spec/turn_spec.rb
board class  
game class
turn class
setup class  
ship spec
board class - test generate cells method and helper methods
game class - update messages with spaces
turn class - test take_turn method and validate_computer_shot method 
setup class  -  update test for run_setup
ship spec - update spec ship name to "rocket" 🚀
Feature updates
See above.
> Refactor all classes and tests

- lib/board.rb
- lib/cell.rb
- lib/game.rb
- lib/setup.rb
- lib/turn.rb
- spec/board_spec.rb
- spec/cell_spec.rb
- spec/setup_spec.rb
Updates Battleship to a space theme and uses emojis in rendering
Makes the UI more fun
feature
Updated all tests to account for new names and emojis
> Refactor game to render with space theme and emojis

- lib/board.rb
- lib/game.rb
- lib/setup.rb
- lib/turn.rb
- spec/setup_spec.rb
Board, Turn, Setup classes and tests
Makes helper methods private and reorganizes class files. Also added relevant tests where needed.
bug fixes for organization
Added tests where needed and checked test files for completeness
> Add tests and make helper methods private

- lib/game.rb
- lib/messages.rb
- lib/setup.rb
- lib/turn.rb
- runner_test.rb
- spec/messages_spec.rb
turn class, setup class and game class
migrates all message strings to new messages class
feature
We created tests for each new messages method
> Create messages class

- lib/game.rb
- lib/setup.rb
- lib/user_input.rb
- spec/user_input_spec.rb
Creates UserInput class
Allows us to refactor methods with user input and enable testing
feature
Tested using runner file
> Create User Input class to refactor user_place_ship method
